apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: matrix-synapse-claim1
  name: matrix-synapse-claim1
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 100Mi
