apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: matrix-synapse-init
  name: matrix-synapse-init
spec:
  containers:
    - args:
        - generate
      env:
        - name: SYNAPSE_REPORT_STATS
          value: "no"
        - name: SYNAPSE_SERVER_NAME
          value: localhost
      image: matrixdotorg/synapse:latest
      name: pupero-matrix-init
      volumeMounts:
        - mountPath: /data
          name: synapse-data
  restartPolicy: Never
  volumes:
    - name: synapse-data
      persistentVolumeClaim:
        claimName: synapse-data
