apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: matrix-synapse
  name: matrix-synapse
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: matrix-synapse
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: matrix-synapse
    spec:
      containers:
        - args:
            - run
            - --config-path
            - /data/homeserver.yaml
            - --config-path
            - /data/synapse.overrides.yaml
          env:
            - name: SYNAPSE_REPORT_STATS
              value: "no"
            - name: SYNAPSE_SERVER_NAME
              value: localhost
          image: matrixdotorg/synapse:latest
          livenessProbe:
            exec:
              command:
                - wget -qO- http://127.0.0.1:8008/_matrix/client/versions >/dev/null 2>&1 || exit 1
            failureThreshold: 60
            initialDelaySeconds: 120
            periodSeconds: 60
            timeoutSeconds: 10
          name: pupero-matrix-synapse
          ports:
            - containerPort: 8008
              protocol: TCP
          volumeMounts:
            - mountPath: /data
              name: synapse-data
            - mountPath: /data/synapse.overrides.yaml
              name: matrix-synapse-claim1
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: synapse-data
          persistentVolumeClaim:
            claimName: synapse-data
        - name: matrix-synapse-claim1
          persistentVolumeClaim:
            claimName: matrix-synapse-claim1
            readOnly: true
