apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: monerod
  name: monerod
spec:
  ports:
    - name: "28080"
      port: 28080
      targetPort: 28080
    - name: "28081"
      port: 28081
      targetPort: 28081
  selector:
    io.kompose.service: monerod
