apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: offers
  name: offers
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: offers
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: offers
    spec:
      containers:
        - env:
            - name: DATABASE_URL
              value: mariadb+mariadbconnector://root:change_this_password@pupero-database:3306/pupero_auth
            - name: OFFERS_PORT
              value: "8002"
          image: pupero-offers
          name: pupero-offers
          ports:
            - containerPort: 8002
              protocol: TCP
      restartPolicy: Always
