apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: transactions
  name: transactions
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: transactions
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: transactions
    spec:
      containers:
        - env:
            - name: DATABASE_URL
              value: mariadb+mariadbconnector://root:change_this_password@pupero-database:3306/pupero_auth
            - name: MONERO_SERVICE_URL
              value: pupero-api-manager
            - name: RABBITMQ_QUEUE
              value: monero.transactions
            - name: RABBITMQ_URL
              value: amqp://pupero:pupero@pupero-rabbitmq:5672/%2F
            - name: TRANSACTIONS_PORT
              value: "8003"
          image: pupero-transactions
          name: pupero-transactions
          ports:
            - containerPort: 8003
              protocol: TCP
      restartPolicy: Always
