{{- if .Values.services.rabbitmq.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pupero.fullname" . }}-rabbitmq
  labels:
    {{- include "pupero.labels" . | nindent 4 }}
    component: rabbitmq
spec:
  type: ClusterIP
  ports:
  - port: 5672
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: {{ include "pupero.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    component: rabbitmq
{{- end }}
