{{- if .Values.services.database.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "pupero.fullname" . }}-database
  labels:
    {{- include "pupero.labels" . | nindent 4 }}
    component: database
spec:
  serviceName: {{ include "pupero.fullname" . }}-database
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "pupero.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      component: database
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "pupero.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        component: database
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: database
        image: {{ include "pupero.image" (dict "repository" .Values.images.database.repository "tag" .Values.images.database.tag "context" $) }}
        imagePullPolicy: {{ .Values.images.database.pullPolicy }}
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: {{ .Values.global.database.rootPassword | quote }}
        - name: MYSQL_DATABASE
          value: {{ .Values.global.database.name | quote }}
        - name: MYSQL_ROOT_HOST
          value: "%"
        ports:
        - name: mysql
          containerPort: 3306
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
        livenessProbe:
          exec:
            command:
            - mariadb-admin
            - ping
            - -uroot
            - -p{{ .Values.global.database.rootPassword }}
            - --silent
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - mariadb-admin
            - ping
            - -uroot
            - -p{{ .Values.global.database.rootPassword }}
            - --silent
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 5
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
  volumeClaimTemplates:
  {{- if .Values.services.database.persistence.enabled }}
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      {{- if .Values.services.database.persistence.storageClass }}
      storageClassName: {{ .Values.services.database.persistence.storageClass | quote }}
      {{- end }}
      resources:
        requests:
          storage: {{ .Values.services.database.persistence.size }}
  {{- end }}
{{- end }}
