{{- if .Values.services.moneroService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pupero.fullname" . }}-monero-service
  labels:
    {{- include "pupero.labels" . | nindent 4 }}
    component: monero-service
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.services.moneroService.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: {{ include "pupero.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    component: monero-service
{{- end }}
